// Code generated by protoc-gen-go. DO NOT EDIT.
// source: def.proto

package proto_conversion

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IntAsString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntAsString) Reset()         { *m = IntAsString{} }
func (m *IntAsString) String() string { return proto.CompactTextString(m) }
func (*IntAsString) ProtoMessage()    {}
func (*IntAsString) Descriptor() ([]byte, []int) {
	return fileDescriptor_76fb0470a3b910d8, []int{0}
}

func (m *IntAsString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntAsString.Unmarshal(m, b)
}
func (m *IntAsString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntAsString.Marshal(b, m, deterministic)
}
func (m *IntAsString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntAsString.Merge(m, src)
}
func (m *IntAsString) XXX_Size() int {
	return xxx_messageInfo_IntAsString.Size(m)
}
func (m *IntAsString) XXX_DiscardUnknown() {
	xxx_messageInfo_IntAsString.DiscardUnknown(m)
}

var xxx_messageInfo_IntAsString proto.InternalMessageInfo

func (m *IntAsString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ShopspringDecimal struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopspringDecimal) Reset()         { *m = ShopspringDecimal{} }
func (m *ShopspringDecimal) String() string { return proto.CompactTextString(m) }
func (*ShopspringDecimal) ProtoMessage()    {}
func (*ShopspringDecimal) Descriptor() ([]byte, []int) {
	return fileDescriptor_76fb0470a3b910d8, []int{1}
}

func (m *ShopspringDecimal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopspringDecimal.Unmarshal(m, b)
}
func (m *ShopspringDecimal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopspringDecimal.Marshal(b, m, deterministic)
}
func (m *ShopspringDecimal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopspringDecimal.Merge(m, src)
}
func (m *ShopspringDecimal) XXX_Size() int {
	return xxx_messageInfo_ShopspringDecimal.Size(m)
}
func (m *ShopspringDecimal) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopspringDecimal.DiscardUnknown(m)
}

var xxx_messageInfo_ShopspringDecimal proto.InternalMessageInfo

func (m *ShopspringDecimal) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*IntAsString)(nil), "proto_conversion.IntAsString")
	proto.RegisterType((*ShopspringDecimal)(nil), "proto_conversion.ShopspringDecimal")
}

func init() { proto.RegisterFile("def.proto", fileDescriptor_76fb0470a3b910d8) }

var fileDescriptor_76fb0470a3b910d8 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x49, 0x4d, 0xd3,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x00, 0x53, 0xf1, 0xc9, 0xf9, 0x79, 0x65, 0xa9, 0x45,
	0xc5, 0x99, 0xf9, 0x79, 0x4a, 0xca, 0x5c, 0xdc, 0x9e, 0x79, 0x25, 0x8e, 0xc5, 0xc1, 0x25, 0x45,
	0x99, 0x79, 0xe9, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x92, 0x26, 0x97, 0x60, 0x70, 0x46, 0x7e, 0x41, 0x71, 0x01, 0x48,
	0x8d, 0x4b, 0x6a, 0x72, 0x66, 0x6e, 0x62, 0x0e, 0x76, 0xa5, 0x49, 0x6c, 0x60, 0x1b, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x3d, 0x4c, 0x72, 0x75, 0x00, 0x00, 0x00,
}
